sudo: required

language: python

python:
  - "3.6"

branches:
  only:
    - master

env:
  - DEVSTACK_WORKSPACE=/tmp SHALLOW_CLONE=1 DEVSTACK='lms'
  - DEVSTACK_WORKSPACE=/tmp SHALLOW_CLONE=1 DEVSTACK='registrar'
  - DEVSTACK_WORKSPACE=/tmp SHALLOW_CLONE=1 DEVSTACK='ecommerce'
  - DEVSTACK_WORKSPACE=/tmp SHALLOW_CLONE=1 DEVSTACK='discovery'
  - DEVSTACK_WORKSPACE=/tmp SHALLOW_CLONE=1 DEVSTACK='forum'
  - DEVSTACK_WORKSPACE=/tmp SHALLOW_CLONE=1 DEVSTACK='analytics_pipeline'

services:
  - docker

before_install:
  # Upgrade Docker to the latest version
  - docker version
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker version
  - docker-compose --version

  - make requirements
  - make dev.clone
  - if [[ $DEVSTACK == 'lms' ]]; then make dev.pull.lms; fi
  - if [[ $DEVSTACK == 'registrar' ]]; then make dev.pull.registrar; fi
  - if [[ $DEVSTACK == 'ecommerce' ]]; then make dev.pull.ecommerce; fi
  - if [[ $DEVSTACK == 'discovery' ]]; then make dev.pull.discovery; fi
  - if [[ $DEVSTACK == 'forum' ]]; then make dev.pull.forum; fi
  - if [[ $DEVSTACK == 'analytics_pipeline' ]]; then make dev.up.analytics_pipeline; fi

script:
  - "./.travis/run.sh"
