version: "2.1"

services:
  edraak_programs:
    volumes:
      - progs-nfs:/app
      - ~/.ssh/:/root/.ssh
      - src-nfs:/edx/src
  edraak_programs_gulp:
    volumes:
      - progs-nfs:/app
      - ~/.ssh/:/root/.ssh
      - src-nfs:/edx/src

volumes:
  src-nfs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: :${DEVSTACK_WORKSPACE}/src
  progs-nfs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: :${DEVSTACK_WORKSPACE}/edraak-programs
