version: "2.1"

services:
  credentials:
    volumes:
      - ${DEVSTACK_WORKSPACE}/credentials:/edx/app/credentials/credentials:cached
  discovery:
      volumes:
      - ${DEVSTACK_WORKSPACE}/course-discovery:/edx/app/discovery/discovery:cached
  ecommerce:
    volumes:
      - ${DEVSTACK_WORKSPACE}/ecommerce:/edx/app/ecommerce/ecommerce:cached
  lms:
    volumes:
      - ${DEVSTACK_WORKSPACE}/edx-platform:/edx/app/edxapp/edx-platform:cached
      - ${DEVSTACK_WORKSPACE}/src:/edx/src:cached
  lms_watcher:
    volumes:
      - ${DEVSTACK_WORKSPACE}/edx-platform:/edx/app/edxapp/edx-platform:cached
  studio:
    volumes:
      - ${DEVSTACK_WORKSPACE}/edx-platform:/edx/app/edxapp/edx-platform:cached
      - ${DEVSTACK_WORKSPACE}/src:/edx/src:cached
  studio_watcher:
    volumes:
      - ${DEVSTACK_WORKSPACE}/edx-platform:/edx/app/edxapp/edx-platform:cached
  forum:
    volumes:
      - ${DEVSTACK_WORKSPACE}/cs_comments_service:/edx/app/forum/cs_comments_service:cached
      
