version: "2.1"

services:
  credentials:
    volumes:
      - ${DEVSTACK_WORKSPACE}/credentials:/edx/app/credentials/credentials:cached
      - credentials_node_modules:/edx/app/credentials/credentials/node_modules
  discovery:
      volumes:
      - ${DEVSTACK_WORKSPACE}/course-discovery:/edx/app/discovery/discovery:cached
      - discovery_node_modules:/edx/app/discovery/discovery/node_modules
  ecommerce:
    volumes:
      - ${DEVSTACK_WORKSPACE}/ecommerce:/edx/app/ecommerce/ecommerce:cached
      - ecommerce_node_modules:/edx/app/ecommerce/ecommerce/node_modules
  lms:
    volumes:
      - ${DEVSTACK_WORKSPACE}/edx-platform:/edx/app/edxapp/edx-platform:cached
      - edxapp_node_modules:/edx/app/edxapp/edx-platform/node_modules
      - ${DEVSTACK_WORKSPACE}/src:/edx/src:cached
  studio:
    volumes:
      - ${DEVSTACK_WORKSPACE}/edx-platform:/edx/app/edxapp/edx-platform:cached
      - edxapp_node_modules:/edx/app/edxapp/edx-platform/node_modules
      - ${DEVSTACK_WORKSPACE}/src:/edx/src:cached
  forum:
    volumes:
      - ${DEVSTACK_WORKSPACE}/cs_comments_service:/edx/app/forum/cs_comments_service:cached
      
volumes:
  credentials_node_modules:
  discovery_node_modules:
  ecommerce_node_modules:
  edxapp_node_modules:
