version: "2.1"

services:
  edraak_programs:
    volumes:
      - ${DEVSTACK_WORKSPACE}/edraak-programs:/app:cached
      - ~/.ssh/:/root/.ssh
      - ${DEVSTACK_WORKSPACE}/src:/src:cached
  edraak_programs_gulp:
    volumes:
      - ${DEVSTACK_WORKSPACE}/edraak-programs:/app:cached
      - ~/.ssh/:/root/.ssh
      - ${DEVSTACK_WORKSPACE}/src:/src:cached

volumes:
#  credentials_node_modules:
#  discovery_node_modules:
#  ecommerce_node_modules:
